// NOTE: unlike the rest of this package, this file is hand-written rather
// than generated by orval. Payment endpoints aren't in lib/api-spec/openapi.yaml
// yet — if you want that consistency back, add /payments/charge, /submit-otp,
// and /verify/{reference} to the spec and regenerate; this file can then be
// deleted in favor of the generated hooks.
import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetch } from "@workspace/api-client-react/custom-fetch";

// POST /payments/charge — kicks off a MoMo charge for an order.
export function useChargeMobileMoney() {
  return useMutation({
    mutationFn: ({ orderId, phone, provider }) =>
      customFetch("/api/v1/payments/charge", {
        method: "POST",
        body: JSON.stringify({ orderId, phone, provider }),
        responseType: "json",
      }),
  });
}

// POST /payments/submit-otp — only needed when the charge response's
// status was "send_otp" (e.g. Vodafone/Telecel Cash).
export function useSubmitPaymentOtp() {
  return useMutation({
    mutationFn: ({ reference, otp }) =>
      customFetch("/api/v1/payments/submit-otp", {
        method: "POST",
        body: JSON.stringify({ reference, otp }),
        responseType: "json",
      }),
  });
}

// GET /payments/verify/:reference — poll this while waiting for the
// customer to approve the charge on their phone. Passing `enabled` lets
// the caller turn polling on only once a charge is actually in flight.
export function useVerifyPayment(reference, { enabled = false } = {}) {
  return useQuery({
    queryKey: ["verifyPayment", reference],
    queryFn: () =>
      customFetch(`/api/v1/payments/verify/${reference}`, {
        method: "GET",
        responseType: "json",
      }),
    enabled: enabled && !!reference,
    // Keep polling every 3s until the status is no longer "pending" —
    // stop once we get a definitive success/failed so we don't hammer the API.
    refetchInterval: (query) => {
      const status = query.state.data?.status;
      if (status === "success" || status === "failed") return false;
      return 3000;
    },
  });
}