// NOTE: hand-written rather than generated by orval — payment endpoints
// aren't in lib/api-spec/openapi.yaml yet. Add /payments/initialize and
// /payments/finalize/{reference} there and regenerate if you want this
// folded back into the generated client later.
import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetch } from "@workspace/api-client-react/custom-fetch";

// POST /payments/initialize — starts a hosted Paystack checkout for a
// produce purchase. Returns { authorizationUrl, reference }; the caller
// should redirect the browser to authorizationUrl (window.location.href =
// ..., NOT a SPA navigation, since it's an external Paystack page).
export function useInitializeCheckout() {
  return useMutation({
    mutationFn: ({ produceId, quantityKg, deliveryAddress, notes, isDeposit }) =>
      customFetch("/api/v1/payments/initialize", {
        method: "POST",
        body: JSON.stringify({ produceId, quantityKg, deliveryAddress, notes, isDeposit }),
        responseType: "json",
      }),
  });
}

// GET /payments/finalize/:reference — call this once, on the
// /payment/callback page, after Paystack redirects the buyer back.
// This is what actually creates the order server-side.
export function useFinalizeOrder(reference, { enabled = true } = {}) {
  return useQuery({
    queryKey: ["finalizeOrder", reference],
    queryFn: () =>
      customFetch(`/api/v1/payments/finalize/${reference}`, {
        method: "GET",
        responseType: "json",
      }),
    enabled: enabled && !!reference,
    retry: false, // don't silently retry a payment finalization
  });
}